"vimrc initial confi"
set exrc
set secure

"Pathogen"
execute pathogen#infect()

"default bash"
set shell=/bin/bash

"Line Numbers"
set number

"Scrolling"
set scrolloff=5
set scrolljump=5

"Tab spaces"
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab|retab!

"Line break highlighting"
set colorcolumn=110
highlight ColorColumn ctermbg=red

"Color Theme"
syntax enable
set background=dark
colorscheme solarized

"File type detection"
augroup project
	autocmd!
	autocmd BufRead,BufNewFile *.h,*.c set filetype=c.doxygen
	autocmd BufRead,BufNewFile *.md set filetype=markdown
	autocmd BufRead,BufNewFile *.py,*.sage set filetype=python
augroup END

"Ignore on complete"
set wildignore=.svn,CVS,.git,.hg,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif
"Ignore when opening from tree"
let g:netrw_list_hide= '.*\.swp$,.*\.gcda$,.*\.gcno$,.*\.o$'

"cmd"
nnoremap <F2> :<C-U>setlocal lcs=tab:>-,trail:-,eol:$ list! list? <CR>
nnoremap <F4> :make!<cr>
nnoremap <F5> :!./run.out<cr>
nnoremap <F8> :vertical wincmd f<CR>
nnoremap <silent> <F9> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR> gg=G

"Move lines up and down"
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv


"Syntastic"
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_remove_include_errors = 1

"RUST"
let g:rustfmt_autosave = 1


"STATUSBAR
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
set laststatus=2 " Always display the statusline in all windows 
set showtabline=2 " Always display the tabline, even if there is only one tab 
set noshowmode

"replace beep sound for flashing
set visualbell
